### ISSUE TITLE
Failed to load load_image.bmp

### ISSUE THREAD

**Issue by Vasilis553** [fufesou/RustDeskTempTopMostWindow#2]
As I though yesterday after my issues on privacy with dll on topmost 0.2 I downloaded topmost pre release and v0.3 I builded them and I tried to load the bmp file in img.cpp and failed on both but I tried to load to topmost v0.2 and succeeded 

![Screenshot_2024-03-09-23-14-43-954_com carriez flutter_hbb](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/108126638/cbb28341-c4b3-496d-863c-ef722ad7362a)
![Screenshot_2024-03-09-23-21-20-025_com carriez flutter_hbb](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/108126638/b4b88c98-48cd-4b9b-a256-8d53e55ff669)

**Comment by fufesou** [comment]
Thanks for your feedback.

You need to create a directory for the outfile.

![image](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/13586388/ffd90095-8eb6-400d-b876-eec7cf625df7)

It must be the only reason.

https://github.com/fufesou/RustDeskTempTopMostWindow/blob/b07778816b1f814a44be45148c6b107201d3cec1/Img2Mem/main.cpp#L97

`.\Img2Mem.exe` should better run directly in the vs solution.

<img width="367" alt="1710032942343" src="https://github.com/fufesou/RustDeskTempTopMostWindow/assets/13586388/df9cd90b-52d4-473e-84ee-0ea6c04392dd">

**Comment by Vasilis553** [comment]
I loaded the bmp but then error in vs when I tried to rebuild the solution
![Screenshot_2024-03-10-09-22-06-866_com carriez flutter_hbb](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/108126638/ca08b563-68fc-45dd-8c68-7843b334565c)

**Comment by fufesou** [comment]
![image](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/13586388/4a31814e-5eea-4ddb-a172-a92c243d6f35)

You need to make sure the file can be accessed.

**Comment by Vasilis553** [comment]
Thanks a lot for this!
I've made it and on my Win11 computer 1.2.4 worked nice but when I tried to replace the dll to my win10 system sais no privacy mode created but if I put the dll that gets with the app it works fine

**Comment by fufesou** [comment]
> when I tried to replace the dll to my win10 system sais no privacy mode created

It may because the topmost window cannot be created.

You may refer to the logs

```
installed version: C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log

non-installed version: %appdata%\rustdesk\log\rustdesk_rCURRENT.log
```

> in the windows 10 pc test app says MSVCP140.DLL not found

You need to make sure the runtime is ok.

**Comment by Vasilis553** [comment]
Runtime works fine
And on topmost v0.2 it runs perfect
But same time topmost vpre-release
Shows errors:MSVCP140. dll, vcruntime140d.dll,vcruntime140_1d.dll,ucrtbase.dll only on 2 computers running win 10.
On the Win11 topmost pre release and privacy works fine

**Comment by fufesou** [comment]
They're different.

"topmost v0.2" is built from my PC.

The pre-release is built from the github ci. You PC may lake those DLLs.

I'll try copy those DLLs to the pre-built package.

**Comment by Vasilis553** [comment]
Ive added the dlls on sys32 restarted still get those 4errors happening on the prebuild.

**Comment by fufesou** [comment]
> Ive added the dlls on sys32 restarted still get those 4errors happening on the prebuild.

No need to put the dlls in the sys23 dir. You may google how to solve those errors.

**Comment by Vasilis553** [comment]
> > Ive added the dlls on sys32 restarted still get those 4errors happening on the prebuild.
> 
> No need to put the dlls in the sys23 dir. You may google how to solve those errors.

You can close this issue it need to the computer that you want to use the tempmost v0.3 or topmostgit to have installed the vsstudio19 somehow only then it works! otherwise we get error for the dlls!!
and one more thing (Do you have archive of nighly .exe and .apk with the privacy mode 2 with the driver ? i wasnt able to make a nighly build)

**Comment by fufesou** [comment]
> otherwise we get error for the dlls!!

What errors you have get?

>  i wasnt able to make a nighly build)

No. I don't have one.
But I'll try create a new branch that can work with CI. You can then fetch or fork it. Run the CI by yourself.

**Comment by fufesou** [comment]
There's another issue that the second privacy mode needs Indirect display driver, which will also need a cert.

Please make sure you're Ok with https://github.com/rustdesk/rustdesk/discussions/6444

There's another bug that it will create some strange directories, "ROOT\0" encoded as UTF-16 ("佒呏"). There's no contents, but the directory seems very strange. 

I'm still tring to find out the reason.

https://github.com/rustdesk/rustdesk/discussions/6444#discussioncomment-9007009

Google Translate seems to have been set up haphazardly. This is garbled code and has been translated into very bad content.

**Comment by fufesou** [comment]
You can 

1. Create a new tag and a new pre-release named nightly.
2. Fork and run the action 
<img width="1064" alt="1712284877461" src="https://github.com/fufesou/RustDeskTempTopMostWindow/assets/13586388/9eb1c52a-20ab-4fa0-a113-7b7d5f2a93e8">
3. Wait the workflow end
![image](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/13586388/7d4382f0-c533-4c79-a96d-720993e98b1d)
4. Download the built app in your release-ngihtly page.

**Comment by fufesou** [comment]
You can also download mine. But it may be replaced the next time a Nightly workflow is triggered.

**Comment by Vasilis553** [comment]
![IMG_20240405_061959](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/108126638/8e1ec2aa-2463-48b7-af2c-0cff63dfa8a4)
I don't see the run workflow

**Comment by fufesou** [comment]
That's my repo. You need to fork and trigger the workflow in your own repo.

**Comment by Vasilis553** [comment]
I don't get something in action tab is empty

**Comment by Vasilis553** [comment]
![Screenshot_2024-04-05-06-46-52-847_com android chrome](https://github.com/fufesou/RustDeskTempTopMostWindow/assets/108126638/6741abb3-55c6-49fb-891a-9bd78321a5a6)
Maybe ready and I wait to download?

**Comment by fufesou** [comment]
The branch is wrong.

You need to fetch and choose the correct branch.

```bash
git remote add fufesou https://github.com/fufesou/rustdesk
git fetch fufesou tmp/privacy_mode_for_6406:tmp/privacy_mode_for_6406
git checkout tmp/privacy_mode_for_6406
git push origin tmp/privacy_mode_for_6406
```

And then trigger the workflow, choose the branch, run again.

Please also be sure that you have "Create a new tag and a new pre-release named nightly."
